language: cpp
env:
  global:
    - SHARED=OFF
    - BUILD_DEPENDENCY_FROM_SOURCE=OFF
    - BUILD_TENSORFLOW_OPS=ON
    - BUILD_CUDA_MODULE=OFF
    - NPROC=2

notifications:
  email:
    on_success: never
    on_failure: always

matrix:

  include:
    # Style check only
    - os: linux
      dist: bionic
      sudo: true
      language: python
      python: "3.6"
      script:
        - ls
