language: cpp
env:
  global:
    - NPROC=2

jobs:
  include:
    # Ubuntu 20.04 ARM, with compatible cmake version
    - name: Ubuntu ARM
      os: linux
      arch: arm64
      dist: focal
      language: python
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - gfortran
            - libblas-dev
            - liblapack-dev
            - liblapacke-dev
      install:
        # Ubuntu dependencies
        - ./util/install_deps_ubuntu.sh assume-yes
        # Check versions
        - python --version
        - python3 --version
        - pip --version
        # Python dependencies
        - pip install -U pytest=="6.0.1"
      script:
        # Build
        - mkdir build
        - pushd build
        - |
          cmake \
            -DUSE_BLAS=ON \
            -DBUILD_GUI=OFF \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_CUDA_MODULE=OFF \
            -DBUILD_TENSORFLOW_OPS=OFF \
            -DBUILD_PYTORCH_OPS=OFF \
            -DBUILD_RPC_INTERFACE=ON \
            -DCMAKE_INSTALL_PREFIX="~/open3d_install" \
            -DPYTHON_EXECUTABLE="$(which python)" \
            -DBUILD_UNIT_TESTS=ON \
            -DBUILD_BENCHMARKS=ON \
            -DBUILD_EXAMPLES=ON \
            ..
        - make -j$(proc)
        - make install -j$(proc)
        - make install-pip-package -j$(proc)
        # Test
        - ./bin/tests --gtest_filter="-*Reduce*Sum*"
        - pytest ../python/test/core --ignore ../python/test/ml_ops/
        # Clean up
        - popd # build
