name: Windows CI

on:
  workflow_dispatch:
    inputs:
      developer_build:
        description: 'Set to OFF for Release wheels'
        required: false
        default: 'ON'

  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]    # Rebuild on new pushes to PR

env:
  PIP_VER: "20.2.2"
  WHEEL_VER: "0.35.1"
  PYTEST_VER: "6.0.1"
  SCIPY_VER: "1.4.1"       # Needed by Tensorflow 2.3.0
  NPROC: 2

jobs:
  build-wheel:
    name: Build wheel
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.6]
    env:
      DEVELOPER_BUILD: ${{ github.event.inputs.developer_build }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python version
        uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: false
          python-version: ${{ matrix.python_version }}

      - name: Config
        shell: pwsh
        run: |
          mkdir build
          cd build
          if (${env:DEVELOPER_BUILD} -ne "OFF") {
            ${env:DEVELOPER_BUILD}="ON"
          }
          cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="C:\Program Files\Open3D" -DBUILD_SHARED_LIBS=OFF -DSTATIC_WINDOWS_RUNTIME=ON -DDEVELOPER_BUILD="${env:DEVELOPER_BUILD}" ..

      - name: Build Python package
        shell: pwsh
        run: |
          python -m pip install --upgrade pip==${{ env.PIP_VER }}
          python -m pip install -U wheel==${{ env.WHEEL_VER }}
          cd build
          cmake --build . --parallel ${{ env.NPROC }} --config Release --target install-pip-package
          $PIP_PKG_NAME=(Get-ChildItem lib/python_package/pip_package/open3d*.whl).Name
          echo "PIP_PKG_NAME=$PIP_PKG_NAME"  | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          conda install conda-build -y
          cmake --build . --config Release --target conda-package
          $CONDA_PKG_NAME=(Get-ChildItem lib/python_package/conda_package/open3d*.tar.bz2).Name
          echo "CONDA_PKG_NAME=$CONDA_PKG_NAME"  | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

