name: Windows CI

on:
  workflow_dispatch:
    inputs:
      developer_build:
        description: 'Set to OFF for Release wheels'
        required: false
        default: 'ON'

  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]    # Rebuild on new pushes to PR

env:
  PIP_VER: "20.2.2"
  WHEEL_VER: "0.35.1"
  PYTEST_VER: "6.0.1"
  SCIPY_VER: "1.4.1"       # Needed by Tensorflow 2.3.0

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        SHARED: [ON, OFF]
        STATIC_RUNTIME: [ON, OFF]
        CONFIG: [Release, Debug]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python version
        uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: 3.6
      - name: Config
        run: |
          python --version
          conda --version
